#SPDX-License-Identifier: MIT-0
---
# tasks file for junos_configure_ospf

- name: "Task1: [[task_one_name]]"
  junipernetworks.junos.junos_config: #THIS IS THE MODULE NAME
    src: "{{ ospf_templaye }}"
  register: ospf_result

- name: "Task 2: {{ task_two_name }}"
  debug:
    msg: "{{ ospf_result }}"

- name: "Task3: {{task_three_name }}"
  junipernetworks.junos.junos_command:
    commands:
    - "{{ ospf_show_command}}"
  register: show__ospf_output

- name: "Task4: Task_four_result"
  debug:
        msg: "{{ show__ospf_output.stdout[0].split('\n') }}"
