---

- name: "get facts play"
  hosts: all
  connection: network_netconf

  tasks:
    - name: collect default set of facts and configuration
      junipernetworks.junos.junos_facts:
        gather_subset: config
        config_format: xml
      register: junos_facts_output

    - name: "print the junos output varibale"
      debug:
        msg: "{{ junos_facts_output }}"